name: 'hello-world-docker-astion'
description: 'Say hello to a user or the world.'
input:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'world'
  outputs:
    time:
      description: 'The time we said hello.'
    runs:
      using: 'docker'
      image: 'Dockerfile'
      args:
        - ${{inputs.who-to-greet}}
