name: GitHub Actions Demo
on:
  push:
    branches: 
      - main
    paths-ignore: 
      - .github/**
  pull_request:
    branches: 
      -main
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "event name: ${{ github.event_name }}"
          echo "event ref: ${{ github.ref }} "
          
      - uses: actions/checkout@v4.0.0

      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree
